=== fischer-ncar/cime/cime_config/acme/machines/config_machines.dtd
<!ELEMENT DIN_LOC_ROOT_CLMFORC (#PCDATA)>
<!ELEMENT PROJECT_REQUIRED (#PCDATA)>
<!ELEMENT default_run_misc_suffix (#PCDATA)>
<!ELEMENT default_run_suffix (#PCDATA | default_run_exe | default_run_misc_suffix)*>
<!ELEMENT DESC (#PCDATA)>
<!ELEMENT CESMSCRATCHROOT (#PCDATA)>
<!ELEMENT environment_variables (#PCDATA | env)*>
<!ATTLIST environment_variables compiler CDATA #IMPLIED>
<!ATTLIST environment_variables mpilib CDATA #IMPLIED>
<!ATTLIST environment_variables debug CDATA #IMPLIED>
<!ELEMENT module_system (#PCDATA | init_path | cmd_path | modules)*>
<!ATTLIST module_system type CDATA #IMPLIED>
<!ELEMENT BATCHSUBMIT (#PCDATA)>
<!ELEMENT RUNDIR (#PCDATA)>
<!ELEMENT walltimes (#PCDATA | walltime)*>
<!ELEMENT SAVE_TIMING_DIR (#PCDATA)>
<!ELEMENT PROJECT (#PCDATA)>
<!ELEMENT BATCHQUERY (#PCDATA)>
<!ELEMENT cmd_path (#PCDATA)>
<!ATTLIST cmd_path lang CDATA #IMPLIED>
<!ELEMENT PIO_BUFFER_SIZE_LIMIT (#PCDATA)>
<!ELEMENT config_machines (#PCDATA | machine | default_run_suffix)*>
<!ELEMENT modules (#PCDATA | command)*>
<!ATTLIST modules debug CDATA #IMPLIED>
<!ATTLIST modules compiler CDATA #IMPLIED>
<!ATTLIST modules mpilib CDATA #IMPLIED>
<!ELEMENT PES_PER_NODE (#PCDATA)>
<!ELEMENT DOUT_S (#PCDATA)>
<!ELEMENT MAX_TASKS_PER_NODE (#PCDATA)>
<!ELEMENT GMAKE_J (#PCDATA)>
<!ELEMENT batch_system (#PCDATA | queues | walltimes)*>
<!ATTLIST batch_system type CDATA #IMPLIED>
<!ATTLIST batch_system version CDATA #IMPLIED>
<!ELEMENT GMAKE (#PCDATA)>
<!ELEMENT DOUT_S_ROOT (#PCDATA)>
<!ELEMENT BATCHREDIRECT (#PCDATA)>
<!ELEMENT TESTS (#PCDATA)>
<!ELEMENT PROXY (#PCDATA)>
<!ELEMENT COMPILERS (#PCDATA)>
<!ELEMENT walltime (#PCDATA)>
<!ATTLIST walltime ccsm_estcost CDATA #IMPLIED>
<!ATTLIST walltime default CDATA #IMPLIED>
<!ELEMENT CCSM_BASELINE (#PCDATA)>
<!ELEMENT NODENAME_REGEX (#PCDATA)>
<!ELEMENT default_run_exe (#PCDATA)>
<!ELEMENT init_path (#PCDATA)>
<!ATTLIST init_path lang CDATA #IMPLIED>
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg default CDATA #IMPLIED>
<!ATTLIST arg name CDATA #IMPLIED>
<!ELEMENT PERL5LIB (#PCDATA)>
<!ELEMENT CCSM_CPRNC (#PCDATA)>
<!ELEMENT DOUT_L_MSROOT (#PCDATA)>
<!ELEMENT OS (#PCDATA)>
<!ELEMENT env (#PCDATA)>
<!ATTLIST env name CDATA #IMPLIED>
<!ELEMENT executable (#PCDATA)>
<!ATTLIST executable args CDATA #IMPLIED>
<!ELEMENT command (#PCDATA)>
<!ATTLIST command name CDATA #IMPLIED>
<!ELEMENT SUPPORTED_BY (#PCDATA)>
<!ELEMENT machine (#PCDATA | DESC | NODENAME_REGEX | TESTS | OS | COMPILERS | MPILIBS | CESMSCRATCHROOT | RUNDIR | EXEROOT | DIN_LOC_ROOT | DIN_LOC_ROOT_CLMFORC | DOUT_S | DOUT_S_ROOT | DOUT_L_MSROOT | CCSM_BASELINE | CCSM_CPRNC | BATCHQUERY | BATCHSUBMIT | BATCHREDIRECT | SUPPORTED_BY | GMAKE_J | MAX_TASKS_PER_NODE | PES_PER_NODE | batch_system | mpirun | module_system | environment_variables | SAVE_TIMING_DIR | PROJECT | PROJECT_REQUIRED | PIO_CONFIG_OPTS | PROXY | GMAKE | PIO_BUFFER_SIZE_LIMIT | PERL5LIB)*>
<!ATTLIST machine MACH CDATA #IMPLIED>
<!ELEMENT queues (#PCDATA | queue)*>
<!ELEMENT arguments (#PCDATA | arg)*>
<!ELEMENT queue (#PCDATA)>
<!ATTLIST queue walltimemin CDATA #IMPLIED>
<!ATTLIST queue walltimemax CDATA #IMPLIED>
<!ATTLIST queue jobmin CDATA #IMPLIED>
<!ATTLIST queue jobmax CDATA #IMPLIED>
<!ATTLIST queue default CDATA #IMPLIED>
<!ELEMENT mpirun (#PCDATA | executable | arguments)*>
<!ATTLIST mpirun mpilib CDATA #IMPLIED>
<!ELEMENT PIO_CONFIG_OPTS (#PCDATA)>
<!ELEMENT MPILIBS (#PCDATA)>
<!ELEMENT EXEROOT (#PCDATA)>
<!ELEMENT DIN_LOC_ROOT (#PCDATA)>

=== fischer-ncar/cime/cime_config/acme/machines/config_machines.template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config_machines SYSTEM "file:/Users/Andi/Development/ESMCI/cime/cime_config/acme/machines/config_machines.dtd">

<config_machines>
    <machine MACH="MACHINE NAME">
        <DESC>DESCRIPTION OF THE MACHINE</DESC>                             <!-- can be anything -->
        <NODENAME_REGEX>MACHINE</NODENAME_REGEX>                            <!-- regex for auto-detect that you're on this machine -->
        <TESTS>acme_developer</TESTS>                                       <!-- preferred test suite to run on this machine -->
        <OS>USERDEFINED_required_macros</OS>                                <!-- LINUX,Darwin,CNL,AIX,BGL,BGP -->
        <COMPILERS>intel,ibm,pgi,pathscale,gnu,cray,nag</COMPILERS>         <!-- intel,ibm,pgi,pathscale,gnu,cray,nag -->
        <MPILIBS>openmpi,mpich,mpt,mpt,ibm,mpi-serial</MPILIBS>                <!-- openmpi, mpich, ibm, mpi-serial -->
        <CESMSCRATCHROOT>USERDEFINED_required_build</CESMSCRATCHROOT>                     <!-- complete path to the 'scratch' directory -->
        <RUNDIR>USERDEFINED_required_build</RUNDIR>                       <!-- complete path to the run directory -->
        <EXEROOT>USERDEFINED_required_build</EXEROOT>                     <!-- complete path to the build directory -->
        <DIN_LOC_ROOT>USERDEFINED_required_build</DIN_LOC_ROOT>           <!-- complete path to the inputdata directory -->
        <DIN_LOC_ROOT_CLMFORC>USERDEFINED_optional_build</DIN_LOC_ROOT_CLMFORC> <!-- path to the optional forcing data for CLM (for CRUNCEP forcing) -->
        <DOUT_S>FALSE</DOUT_S>                                            <!-- logical for short term archiving -->
        <DOUT_S_ROOT>USERDEFINED_optional_run</DOUT_S_ROOT>               <!-- complete path to a short term archiving directory -->
        <DOUT_L_MSROOT>USERDEFINED_optional_run</DOUT_L_MSROOT>           <!-- complete path to a long term archiving directory -->
        <CCSM_BASELINE>USERDEFINED_optional_run</CCSM_BASELINE>           <!-- where the cesm testing scripts write and read baseline results -->
        <CCSM_CPRNC>USERDEFINED_optional_test</CCSM_CPRNC>                <!-- path to the cprnc tool used to compare netcdf history files in testing -->
        <BATCHQUERY>USERDEFINED_optional_run</BATCHQUERY>
        <BATCHSUBMIT>USERDEFINED_optional_run</BATCHSUBMIT>
        <BATCHREDIRECT></BATCHREDIRECT>
        <SUPPORTED_BY>USERDEFINED_optional</SUPPORTED_BY>
        <GMAKE_J>1</GMAKE_J>
        <MAX_TASKS_PER_NODE>USERDEFINED_required_build</MAX_TASKS_PER_NODE>
        
        <batch_system type="Batchsystem name" version="Version Numer x.y">
            <queues>
                <queue walltimemax="hh:mm:ss" jobmin="1" jobmax="130181" >regular</queue>
                <queue walltimemax="00:30:00" jobmin="1" jobmax="12288" default="true">debug</queue>
            </queues>
            <walltimes>
                <walltime default="true">00:30:00</walltime>
            </walltimes>
        </batch_system>
        
        <mpirun mpilib="default">
            <executable args="">mpirun</executable>
            <arguments>
                <arg name="" default=""></arg>      
            </arguments>
        </mpirun>
        
        <!-- Module system of machine, dependencies for compiler and mpilib combinations -->
        <module_system type="Name of modue system, prefix for module system commands, e.g. 'module'">
            
            <!-- list of init_path elements, one per supported language e.g. sh, perl, python-->
            <init_path lang="perl">PATH</init_path>
           
            <!-- list of cmd_path elements, one for every supported language, e.g. sh, perl, python -->
            <cmd_path lang="perl">e.g. /opt/modules/default/bin/modulecmd perl</cmd_path>
            <cmd_path lang="python">e.g. /opt/modules/default/bin/modulecmd python</cmd_path>
            <cmd_path lang="sh">module</cmd_path>
            

            <!-- List of modules elements, executing commands 
                if compiler and mpilib condition applies -->
            
            <!-- Always execute -->
            <modules> 
                <command name="rm">intel</command>
                <command name="rm">pmi</command>
            </modules>
            
            <!-- If compiler is  $C -->
            <modules compiler="e.g. intel">  
                <!-- List of command elements -->
                <command name="e.g. load, add, switch">Option, e.g. module name</command>
            </modules>
            
            <!-- If compiler is $C and mpilib $M -->
            <modules compiler="e.g. intel" mpilib="e.g. mpi-serial" >
                <command name="Module command">Option</command>
            </modules>
            
            <!-- If compiler is $C and not mpilib $M -->
            <modules compiler="intel" mpilib="!mpi-serial" >
                <command name=""></command>
            </modules>
           
           <!-- If mpilib is $M -->
            <modules mpilib="mpi-serial">
                <command name=""></command>
                <command name=""></command>
            </modules>
            
        </module_system>
        
        
        <!-- List of environment variable elements, 
            set environment variables depending on compiler and mpilib -->
        
        <!-- Always set -->
        <environment_variables>
            <env name="VARIABlE_NAME">VALUE</env>
        </environment_variables>
        
        <!-- Set if compiler and mpilib  -->
        <environment_variables compiler="" mpilib="">
            <env name="VARIABLE_NAME">VALUE</env>
        </environment_variables>
        
    </machine>

</config_machines>
